import type { SpeciesPreset } from "./speciesTypes";

export const SPECIES_PRESETS = {
  lab_mouse: {
    id: "lab_mouse",
    label: "Laboratory mouse (Mus musculus)",
    commonName: "Laboratory mouse",
    scientificName: "Mus musculus",
    activityPattern: "nocturnal_bimodal",
    circadianMode: "nocturnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [20, 2],
    activeWindowHours: { min: 8, mode: 11, max: 14 },
    dailyMotionMinutes: { min: 120, mode: 240, max: 420 },
    majorRestWindowHours: { min: 8, mode: 10, max: 13 },
    movementBoutMeanMinutes: { min: 2, mode: 6, max: 15 },
    restBoutMeanMinutes: { min: 10, mode: 35, max: 90 },
    movementSpeedMetersPerMinute: { min: 0.7, mode: 1.2, max: 2 },
    circadianPhaseOffsetHours: { min: -1.5, mode: 0, max: 1.5 },
    socialPropensity: { min: 0.35, mode: 0.6, max: 0.9 },
    territoriality: { min: 0.1, mode: 0.25, max: 0.55 },
    seasonalSensitivity: 0.05,
    confidence: "medium",
    notes: "Nocturnal, polyphasic, strain- and housing-dependent. Values are motion-positive simulation priors."
  },
  wild_house_mouse: {
    id: "wild_house_mouse",
    label: "Wild/house mouse (Mus musculus)",
    commonName: "Wild/house mouse",
    scientificName: "Mus musculus",
    activityPattern: "nocturnal_bimodal",
    circadianMode: "nocturnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [20, 3],
    activeWindowHours: { min: 8, mode: 12, max: 15 },
    dailyMotionMinutes: { min: 180, mode: 360, max: 600 },
    majorRestWindowHours: { min: 8, mode: 11, max: 14 },
    movementBoutMeanMinutes: { min: 3, mode: 10, max: 25 },
    restBoutMeanMinutes: { min: 15, mode: 50, max: 150 },
    movementSpeedMetersPerMinute: { min: 0.8, mode: 1.4, max: 2.4 },
    circadianPhaseOffsetHours: { min: -2, mode: 0, max: 2 },
    socialPropensity: { min: 0.2, mode: 0.45, max: 0.8 },
    territoriality: { min: 0.2, mode: 0.45, max: 0.75 },
    seasonalSensitivity: 0.25,
    confidence: "medium",
    notes: "Nocturnal and context-dependent; more variable and territorial than lab mouse cohorts."
  },
  lab_rat: {
    id: "lab_rat",
    label: "Laboratory rat (Rattus norvegicus)",
    commonName: "Laboratory rat",
    scientificName: "Rattus norvegicus",
    activityPattern: "nocturnal_unimodal",
    circadianMode: "nocturnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [22, 2],
    activeWindowHours: { min: 9, mode: 12, max: 15 },
    dailyMotionMinutes: { min: 180, mode: 360, max: 600 },
    majorRestWindowHours: { min: 8, mode: 10, max: 13 },
    movementBoutMeanMinutes: { min: 4, mode: 12, max: 30 },
    restBoutMeanMinutes: { min: 15, mode: 45, max: 120 },
    movementSpeedMetersPerMinute: { min: 0.8, mode: 1.5, max: 2.5 },
    circadianPhaseOffsetHours: { min: -1.5, mode: 0, max: 1.5 },
    socialPropensity: { min: 0.55, mode: 0.75, max: 0.95 },
    territoriality: { min: 0.05, mode: 0.2, max: 0.45 },
    seasonalSensitivity: 0.05,
    confidence: "medium",
    notes: "Nocturnal and social; still polyphasic with rest in both light and dark phases."
  },
  deer_mouse: {
    id: "deer_mouse",
    label: "Deer mouse (Peromyscus maniculatus)",
    commonName: "Deer mouse",
    scientificName: "Peromyscus maniculatus",
    activityPattern: "nocturnal_bimodal",
    circadianMode: "nocturnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [19, 5],
    activeWindowHours: { min: 7, mode: 11, max: 14 },
    dailyMotionMinutes: { min: 180, mode: 360, max: 540 },
    majorRestWindowHours: { min: 8, mode: 11, max: 14 },
    movementBoutMeanMinutes: { min: 3, mode: 10, max: 25 },
    restBoutMeanMinutes: { min: 10, mode: 40, max: 120 },
    movementSpeedMetersPerMinute: { min: 0.8, mode: 1.4, max: 2.4 },
    circadianPhaseOffsetHours: { min: -2, mode: 0, max: 2 },
    socialPropensity: { min: 0.2, mode: 0.45, max: 0.75 },
    territoriality: { min: 0.25, mode: 0.5, max: 0.8 },
    seasonalSensitivity: 0.35,
    confidence: "low-medium",
    notes: "Nocturnal/bimodal archetype; calibrate for study system when telemetry data are available."
  },
  white_footed_mouse: {
    id: "white_footed_mouse",
    label: "White-footed mouse (Peromyscus leucopus)",
    commonName: "White-footed mouse",
    scientificName: "Peromyscus leucopus",
    activityPattern: "nocturnal_bimodal",
    circadianMode: "nocturnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [20, 3],
    activeWindowHours: { min: 7, mode: 11, max: 14 },
    dailyMotionMinutes: { min: 160, mode: 320, max: 520 },
    majorRestWindowHours: { min: 8, mode: 11, max: 14 },
    movementBoutMeanMinutes: { min: 3, mode: 10, max: 25 },
    restBoutMeanMinutes: { min: 10, mode: 40, max: 120 },
    movementSpeedMetersPerMinute: { min: 0.8, mode: 1.4, max: 2.4 },
    circadianPhaseOffsetHours: { min: -2, mode: 0, max: 2 },
    socialPropensity: { min: 0.2, mode: 0.45, max: 0.75 },
    territoriality: { min: 0.25, mode: 0.5, max: 0.8 },
    seasonalSensitivity: 0.35,
    confidence: "low-medium",
    notes: "Nocturnal Peromyscus preset with broad priors for field variability."
  },
  prairie_vole: {
    id: "prairie_vole",
    label: "Prairie vole (Microtus ochrogaster)",
    commonName: "Prairie vole",
    scientificName: "Microtus ochrogaster",
    activityPattern: "crepuscular",
    circadianMode: "cathemeral",
    sleepArchitecture: "ultradian",
    activePeakHours: [6, 18],
    activeWindowHours: { min: 6, mode: 10, max: 16 },
    dailyMotionMinutes: { min: 180, mode: 420, max: 720 },
    majorRestWindowHours: { min: 4, mode: 7, max: 10 },
    movementBoutMeanMinutes: { min: 3, mode: 10, max: 30 },
    restBoutMeanMinutes: { min: 20, mode: 60, max: 180 },
    movementSpeedMetersPerMinute: { min: 0.5, mode: 1.2, max: 2.2 },
    ultradianPeriodMinutes: { min: 90, mode: 180, max: 360 },
    ultradianAmplitude: 0.45,
    circadianPhaseOffsetHours: { min: -2, mode: 0, max: 2 },
    socialPropensity: { min: 0.6, mode: 0.85, max: 0.98 },
    territoriality: { min: 0.05, mode: 0.2, max: 0.5 },
    seasonalSensitivity: 0.4,
    confidence: "medium",
    notes: "Use crepuscular peaks plus ultradian modulation. Social propensity should be high but variable."
  },
  meadow_vole: {
    id: "meadow_vole",
    label: "Meadow vole (Microtus pennsylvanicus)",
    commonName: "Meadow vole",
    scientificName: "Microtus pennsylvanicus",
    activityPattern: "ultradian",
    circadianMode: "cathemeral",
    sleepArchitecture: "ultradian",
    activePeakHours: [6, 18],
    activeWindowHours: { min: 8, mode: 14, max: 20 },
    dailyMotionMinutes: { min: 240, mode: 480, max: 780 },
    majorRestWindowHours: { min: 3, mode: 6, max: 10 },
    movementBoutMeanMinutes: { min: 3, mode: 12, max: 35 },
    restBoutMeanMinutes: { min: 20, mode: 75, max: 180 },
    movementSpeedMetersPerMinute: { min: 0.5, mode: 1.2, max: 2.2 },
    ultradianPeriodMinutes: { min: 60, mode: 180, max: 360 },
    ultradianAmplitude: 0.6,
    circadianPhaseOffsetHours: { min: -3, mode: 0, max: 3 },
    socialPropensity: { min: 0.25, mode: 0.5, max: 0.8 },
    territoriality: { min: 0.2, mode: 0.45, max: 0.75 },
    seasonalSensitivity: 0.6,
    confidence: "medium",
    notes: "Strongly ultradian and context-dependent. Avoid strict nocturnal/diurnal assumptions."
  },
  bank_vole: {
    id: "bank_vole",
    label: "Bank vole (Myodes glareolus)",
    commonName: "Bank vole",
    scientificName: "Myodes glareolus",
    activityPattern: "ultradian",
    circadianMode: "cathemeral",
    sleepArchitecture: "ultradian",
    activePeakHours: [6, 18],
    activeWindowHours: { min: 8, mode: 14, max: 20 },
    dailyMotionMinutes: { min: 240, mode: 480, max: 780 },
    majorRestWindowHours: { min: 3, mode: 6, max: 10 },
    movementBoutMeanMinutes: { min: 3, mode: 12, max: 35 },
    restBoutMeanMinutes: { min: 20, mode: 75, max: 180 },
    movementSpeedMetersPerMinute: { min: 0.5, mode: 1.2, max: 2.2 },
    ultradianPeriodMinutes: { min: 60, mode: 180, max: 360 },
    ultradianAmplitude: 0.55,
    circadianPhaseOffsetHours: { min: -3, mode: 0, max: 3 },
    socialPropensity: { min: 0.25, mode: 0.5, max: 0.8 },
    territoriality: { min: 0.2, mode: 0.45, max: 0.75 },
    seasonalSensitivity: 0.6,
    confidence: "medium",
    notes: "Ultradian/weakly circadian vole archetype."
  },
  red_squirrel: {
    id: "red_squirrel",
    label: "Red squirrel archetype",
    commonName: "Red squirrel archetype",
    scientificName: "Tamiasciurus hudsonicus / Sciurus vulgaris",
    activityPattern: "diurnal_bimodal",
    circadianMode: "diurnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [9, 16],
    activeWindowHours: { min: 6, mode: 9, max: 13 },
    dailyMotionMinutes: { min: 180, mode: 360, max: 600 },
    majorRestWindowHours: { min: 10, mode: 13, max: 16 },
    movementBoutMeanMinutes: { min: 5, mode: 20, max: 60 },
    restBoutMeanMinutes: { min: 20, mode: 90, max: 240 },
    movementSpeedMetersPerMinute: { min: 2, mode: 6, max: 12 },
    circadianPhaseOffsetHours: { min: -1, mode: 0, max: 1 },
    socialPropensity: { min: 0.05, mode: 0.15, max: 0.35 },
    territoriality: { min: 0.6, mode: 0.85, max: 0.98 },
    seasonalSensitivity: 0.8,
    confidence: "medium",
    notes: "Diurnal, territorial, weather- and season-sensitive; red squirrel differs by region."
  },
  fox_squirrel: {
    id: "fox_squirrel",
    label: "Fox squirrel (Sciurus niger)",
    commonName: "Fox squirrel",
    scientificName: "Sciurus niger",
    activityPattern: "diurnal_bimodal",
    circadianMode: "diurnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [8, 17],
    activeWindowHours: { min: 6, mode: 9, max: 13 },
    dailyMotionMinutes: { min: 180, mode: 360, max: 600 },
    majorRestWindowHours: { min: 10, mode: 13, max: 16 },
    movementBoutMeanMinutes: { min: 5, mode: 20, max: 60 },
    restBoutMeanMinutes: { min: 20, mode: 90, max: 240 },
    movementSpeedMetersPerMinute: { min: 2, mode: 6, max: 12 },
    circadianPhaseOffsetHours: { min: -1.5, mode: 0, max: 1.5 },
    socialPropensity: { min: 0.05, mode: 0.2, max: 0.45 },
    territoriality: { min: 0.45, mode: 0.7, max: 0.95 },
    seasonalSensitivity: 0.8,
    confidence: "medium",
    notes: "Diurnal; often bimodal morning/evening with seasonal shifts."
  },
  eastern_gray_squirrel: {
    id: "eastern_gray_squirrel",
    label: "Eastern gray squirrel (Sciurus carolinensis)",
    commonName: "Eastern gray squirrel",
    scientificName: "Sciurus carolinensis",
    activityPattern: "diurnal_bimodal",
    circadianMode: "diurnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [8, 16],
    activeWindowHours: { min: 6, mode: 9, max: 13 },
    dailyMotionMinutes: { min: 180, mode: 360, max: 600 },
    majorRestWindowHours: { min: 10, mode: 13, max: 16 },
    movementBoutMeanMinutes: { min: 5, mode: 20, max: 60 },
    restBoutMeanMinutes: { min: 20, mode: 90, max: 240 },
    movementSpeedMetersPerMinute: { min: 2, mode: 6, max: 12 },
    circadianPhaseOffsetHours: { min: -1.5, mode: 0, max: 1.5 },
    socialPropensity: { min: 0.1, mode: 0.25, max: 0.5 },
    territoriality: { min: 0.35, mode: 0.6, max: 0.9 },
    seasonalSensitivity: 0.8,
    confidence: "medium",
    notes: "Diurnal and seasonal; social proximity often reflects shared resources more than stable cohesion."
  },
  ground_squirrel: {
    id: "ground_squirrel",
    label: "Ground squirrel archetype",
    commonName: "Ground squirrel archetype",
    activityPattern: "diurnal_unimodal",
    circadianMode: "diurnal",
    sleepArchitecture: "polyphasic",
    activePeakHours: [12],
    activeWindowHours: { min: 5, mode: 8, max: 12 },
    dailyMotionMinutes: { min: 120, mode: 300, max: 540 },
    majorRestWindowHours: { min: 10, mode: 14, max: 18 },
    movementBoutMeanMinutes: { min: 5, mode: 20, max: 60 },
    restBoutMeanMinutes: { min: 30, mode: 120, max: 300 },
    movementSpeedMetersPerMinute: { min: 2, mode: 6, max: 12 },
    circadianPhaseOffsetHours: { min: -1, mode: 0, max: 1 },
    socialPropensity: { min: 0.05, mode: 0.2, max: 0.45 },
    territoriality: { min: 0.4, mode: 0.7, max: 0.95 },
    seasonalSensitivity: 0.9,
    confidence: "low-medium",
    notes: "Diurnal archetype with strong seasonal/daylight control; hibernation is not modeled."
  },
  human: {
    id: "human",
    label: "Human",
    commonName: "Human",
    scientificName: "Homo sapiens",
    activityPattern: "diurnal",
    circadianMode: "diurnal",
    sleepArchitecture: "monophasic",
    activePeakHours: [14],
    sleepCenterHour: 3,
    activeWindowHours: { min: 12, mode: 15, max: 18 },
    dailyMotionMinutes: { min: 720, mode: 900, max: 1080 },
    majorRestWindowHours: { min: 6, mode: 8, max: 10 },
    movementBoutMeanMinutes: { min: 5, mode: 20, max: 90 },
    restBoutMeanMinutes: { min: 300, mode: 480, max: 600 },
    stationaryAwakeBoutMeanMinutes: { min: 10, mode: 45, max: 180 },
    movementSpeedMetersPerMinute: { min: 40, mode: 80, max: 120 },
    circadianPhaseOffsetHours: { min: -2, mode: 0, max: 3 },
    socialPropensity: { min: 0.15, mode: 0.55, max: 0.9 },
    territoriality: { min: 0.05, mode: 0.15, max: 0.35 },
    groupSynchrony: { min: 0.5, mode: 0.8, max: 0.95 },
    seasonalSensitivity: 0.1,
    lightPhaseStartHour: 7,
    lightPhaseEndHour: 19,
    confidence: "high",
    notes: "Comparison species with consolidated nocturnal sleep, strong social entrainment, and high chronotype variation."
  }
} as const satisfies Record<string, SpeciesPreset>;

export type SpeciesPresetId = keyof typeof SPECIES_PRESETS;

export const DEFAULT_SPECIES_PRESET_ID: SpeciesPresetId = "lab_mouse";

export const speciesPresetOptions = Object.values(SPECIES_PRESETS);

